/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exercise_interview;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LinkedListTest {
    @Test void testExample() {
        assertTrue(2, 1 + 1);
    }
}
